export interface INotification {
  userId?: string;
  title?: string;
  body?: string;
  data?: any;
  isRead?: boolean;
  _id?: string;
  createdAt?: string;
}

export enum ENotificationType {
  SESSION_NO_EYE_AVAILABLE = 'SESSION_NO_EYE_AVAILABLE',
  SESSION_MATCHED = 'SESSION_MATCHED',
  SESSION_REQUEST = 'SESSION_REQUEST',
  EYE_SESSION_CONNECTED = 'EYE_SESSION_CONNECTED',
  SEEKER_SESSION_CONNECTED = 'SEEKER_SESSION_CONNECTED',
  SESSION_ENDED = 'SESSION_ENDED',
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  BOOKING_SESSION_STARTING = 'BOOKING_SESSION_STARTING',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
}
