export interface ICountry {
  name: string;
  flag: string; // Will store emoji
  dialCode: string;
  code: string;
  regex: RegExp;
}

// Regex Patterns
const REGEX_10 = /^\d{10}$/; // Common (US, India, etc.)
const REGEX_9 = /^\d{9}$/; // Common (Europe, Africa)
const REGEX_8 = /^\d{8}$/; // Common (Small nations, Singapore)
const REGEX_11 = /^\d{11}$/; // China, UK, etc.
const REGEX_VARIABLE = /^\d{7,15}$/; // Default variable length
const REGEX_US = /^\d{10}$/; // US, Canada, Caribbean (+1)

// Helper to assign regex based on dial code or country code if specific
const getRegex = (code: string, dialCode: string): RegExp => {
  if (dialCode === '+1') return REGEX_US;
  if (dialCode === '+91') return REGEX_10; // India
  if (dialCode === '+44') return /^\d{10,11}$/; // UK
  if (dialCode === '+86') return REGEX_11; // China
  if (dialCode === '+234') return /^\d{10,11}$/; // Nigeria

  // Region based heuristics could act here, but simple defaults are safer for unknown
  return REGEX_VARIABLE;
};

// Full Country List
export const countryData: ICountry[] = [
  {
    name: 'Afghanistan',
    dialCode: '+93',
    code: 'AF',
    flag: '🇦🇫',
    regex: /^\d{9}$/,
  },
  {
    name: 'Aland Islands',
    dialCode: '+358',
    code: 'AX',
    flag: '🇦🇽',
    regex: /^\d{5,12}$/,
  },
  {
    name: 'Albania',
    dialCode: '+355',
    code: 'AL',
    flag: '🇦🇱',
    regex: /^\d{9}$/,
  },
  {
    name: 'Algeria',
    dialCode: '+213',
    code: 'DZ',
    flag: '🇩🇿',
    regex: /^\d{9,10}$/,
  },
  {
    name: 'American Samoa',
    dialCode: '+1684',
    code: 'AS',
    flag: '🇦🇸',
    regex: REGEX_US,
  },
  {
    name: 'Andorra',
    dialCode: '+376',
    code: 'AD',
    flag: '🇦🇩',
    regex: /^\d{6,9}$/,
  },
  {
    name: 'Angola',
    dialCode: '+244',
    code: 'AO',
    flag: '🇦🇴',
    regex: /^\d{9}$/,
  },
  {
    name: 'Anguilla',
    dialCode: '+1264',
    code: 'AI',
    flag: '🇦🇮',
    regex: REGEX_US,
  },
  {
    name: 'Antarctica',
    dialCode: '+672',
    code: 'AQ',
    flag: '🇦🇶',
    regex: REGEX_VARIABLE,
  },
  {
    name: 'Antigua and Barbuda',
    dialCode: '+1268',
    code: 'AG',
    flag: '🇦🇬',
    regex: REGEX_US,
  },
  {
    name: 'Argentina',
    dialCode: '+54',
    code: 'AR',
    flag: '🇦🇷',
    regex: /^\d{10,11}$/,
  },
  {
    name: 'Armenia',
    dialCode: '+374',
    code: 'AM',
    flag: '🇦🇲',
    regex: /^\d{8}$/,
  },
  { name: 'Aruba', dialCode: '+297', code: 'AW', flag: '🇦🇼', regex: /^\d{7}$/ },
  {
    name: 'Australia',
    dialCode: '+61',
    code: 'AU',
    flag: '🇦🇺',
    regex: /^\d{9}$/,
  },
  {
    name: 'Austria',
    dialCode: '+43',
    code: 'AT',
    flag: '🇦🇹',
    regex: /^\d{10,14}$/,
  },
  {
    name: 'Azerbaijan',
    dialCode: '+994',
    code: 'AZ',
    flag: '🇦🇿',
    regex: /^\d{9}$/,
  },
  {
    name: 'Bahamas',
    dialCode: '+1242',
    code: 'BS',
    flag: '🇧🇸',
    regex: REGEX_US,
  },
  {
    name: 'Bahrain',
    dialCode: '+973',
    code: 'BH',
    flag: '🇧🇭',
    regex: /^\d{8}$/,
  },
  {
    name: 'Bangladesh',
    dialCode: '+880',
    code: 'BD',
    flag: '🇧🇩',
    regex: /^\d{10}$/,
  },
  {
    name: 'Barbados',
    dialCode: '+1246',
    code: 'BB',
    flag: '🇧🇧',
    regex: REGEX_US,
  },
  {
    name: 'Belarus',
    dialCode: '+375',
    code: 'BY',
    flag: '🇧🇾',
    regex: /^\d{9}$/,
  },
  {
    name: 'Belgium',
    dialCode: '+32',
    code: 'BE',
    flag: '🇧🇪',
    regex: /^\d{9}$/,
  },
  {
    name: 'Belize',
    dialCode: '+501',
    code: 'BZ',
    flag: '🇧🇿',
    regex: /^\d{7}$/,
  },
  { name: 'Benin', dialCode: '+229', code: 'BJ', flag: '🇧🇯', regex: /^\d{8}$/ },
  {
    name: 'Bermuda',
    dialCode: '+1441',
    code: 'BM',
    flag: '🇧🇲',
    regex: REGEX_US,
  },
  {
    name: 'Bhutan',
    dialCode: '+975',
    code: 'BT',
    flag: '🇧🇹',
    regex: /^\d{7,8}$/,
  },
  {
    name: 'Bolivia',
    dialCode: '+591',
    code: 'BO',
    flag: '🇧🇴',
    regex: /^\d{8}$/,
  },
  {
    name: 'Bosnia and Herzegovina',
    dialCode: '+387',
    code: 'BA',
    flag: '🇧🇦',
    regex: /^\d{8,9}$/,
  },
  {
    name: 'Botswana',
    dialCode: '+267',
    code: 'BW',
    flag: '🇧🇼',
    regex: /^\d{7,8}$/,
  },
  {
    name: 'Brazil',
    dialCode: '+55',
    code: 'BR',
    flag: '🇧🇷',
    regex: /^\d{10,11}$/,
  },
  {
    name: 'British Indian Ocean Territory',
    dialCode: '+246',
    code: 'IO',
    flag: '🇮🇴',
    regex: REGEX_VARIABLE,
  },
  {
    name: 'Brunei Darussalam',
    dialCode: '+673',
    code: 'BN',
    flag: '🇧🇳',
    regex: /^\d{7}$/,
  },
  {
    name: 'Bulgaria',
    dialCode: '+359',
    code: 'BG',
    flag: '🇧🇬',
    regex: /^\d{8,9}$/,
  },
  {
    name: 'Burkina Faso',
    dialCode: '+226',
    code: 'BF',
    flag: '🇧🇫',
    regex: /^\d{8}$/,
  },
  {
    name: 'Burundi',
    dialCode: '+257',
    code: 'BI',
    flag: '🇧🇮',
    regex: /^\d{8}$/,
  },
  {
    name: 'Cambodia',
    dialCode: '+855',
    code: 'KH',
    flag: '🇰🇭',
    regex: /^\d{8,9}$/,
  },
  {
    name: 'Cameroon',
    dialCode: '+237',
    code: 'CM',
    flag: '🇨🇲',
    regex: /^\d{9}$/,
  },
  { name: 'Canada', dialCode: '+1', code: 'CA', flag: '🇨🇦', regex: REGEX_10 },
  {
    name: 'Cape Verde',
    dialCode: '+238',
    code: 'CV',
    flag: '🇨🇻',
    regex: /^\d{7}$/,
  },
  {
    name: 'Cayman Islands',
    dialCode: '+345',
    code: 'KY',
    flag: '🇰🇾',
    regex: REGEX_US,
  },
  {
    name: 'Central African Republic',
    dialCode: '+236',
    code: 'CF',
    flag: '🇨🇫',
    regex: /^\d{8}$/,
  },
  { name: 'Chad', dialCode: '+235', code: 'TD', flag: '🇹🇩', regex: /^\d{8}$/ },
  { name: 'Chile', dialCode: '+56', code: 'CL', flag: '🇨🇱', regex: /^\d{9}$/ },
  { name: 'China', dialCode: '+86', code: 'CN', flag: '🇨🇳', regex: REGEX_11 },
  {
    name: 'Christmas Island',
    dialCode: '+61',
    code: 'CX',
    flag: '🇨🇽',
    regex: REGEX_9,
  },
  {
    name: 'Cocos (Keeling) Islands',
    dialCode: '+61',
    code: 'CC',
    flag: '🇨🇨',
    regex: REGEX_9,
  },
  {
    name: 'Colombia',
    dialCode: '+57',
    code: 'CO',
    flag: '🇨🇴',
    regex: REGEX_10,
  },
  {
    name: 'Comoros',
    dialCode: '+269',
    code: 'KM',
    flag: '🇰🇲',
    regex: /^\d{7}$/,
  },
  { name: 'Congo', dialCode: '+242', code: 'CG', flag: '🇨🇬', regex: /^\d{9}$/ },
  {
    name: 'DR Congo',
    dialCode: '+243',
    code: 'CD',
    flag: '🇨🇩',
    regex: /^\d{9}$/,
  },
  {
    name: 'Cook Islands',
    dialCode: '+682',
    code: 'CK',
    flag: '🇨🇰',
    regex: /^\d{5}$/,
  },
  {
    name: 'Costa Rica',
    dialCode: '+506',
    code: 'CR',
    flag: '🇨🇷',
    regex: /^\d{8}$/,
  },
  {
    name: "Cote d'Ivoire",
    dialCode: '+225',
    code: 'CI',
    flag: '🇨🇮',
    regex: /^\d{10}$/,
  },
  {
    name: 'Croatia',
    dialCode: '+385',
    code: 'HR',
    flag: '🇭🇷',
    regex: /^\d{8,12}$/,
  },
  { name: 'Cuba', dialCode: '+53', code: 'CU', flag: '🇨🇺', regex: /^\d{8}$/ },
  {
    name: 'Cyprus',
    dialCode: '+357',
    code: 'CY',
    flag: '🇨🇾',
    regex: /^\d{8}$/,
  },
  {
    name: 'Czech Republic',
    dialCode: '+420',
    code: 'CZ',
    flag: '🇨🇿',
    regex: /^\d{9}$/,
  },
  {
    name: 'Denmark',
    dialCode: '+45',
    code: 'DK',
    flag: '🇩🇰',
    regex: /^\d{8}$/,
  },
  {
    name: 'Djibouti',
    dialCode: '+253',
    code: 'DJ',
    flag: '🇩🇯',
    regex: /^\d{8}$/,
  },
  {
    name: 'Dominica',
    dialCode: '+1767',
    code: 'DM',
    flag: '🇩🇲',
    regex: REGEX_US,
  },
  {
    name: 'Dominican Republic',
    dialCode: '+1849',
    code: 'DO',
    flag: '🇩🇴',
    regex: REGEX_US,
  },
  {
    name: 'Ecuador',
    dialCode: '+593',
    code: 'EC',
    flag: '🇪🇨',
    regex: /^\d{9}$/,
  },
  {
    name: 'Egypt',
    dialCode: '+20',
    code: 'EG',
    flag: '🇪🇬',
    regex: /^\d{10,11}$/,
  },
  {
    name: 'El Salvador',
    dialCode: '+503',
    code: 'SV',
    flag: '🇸🇻',
    regex: /^\d{8}$/,
  },
  {
    name: 'Equatorial Guinea',
    dialCode: '+240',
    code: 'GQ',
    flag: '🇬🇶',
    regex: /^\d{9}$/,
  },
  {
    name: 'Eritrea',
    dialCode: '+291',
    code: 'ER',
    flag: '🇪🇷',
    regex: /^\d{7}$/,
  },
  {
    name: 'Estonia',
    dialCode: '+372',
    code: 'EE',
    flag: '🇪🇪',
    regex: /^\d{7,8}$/,
  },
  {
    name: 'Ethiopia',
    dialCode: '+251',
    code: 'ET',
    flag: '🇪🇹',
    regex: /^\d{9}$/,
  },
  {
    name: 'Falkland Islands',
    dialCode: '+500',
    code: 'FK',
    flag: '🇫🇰',
    regex: /^\d{5}$/,
  },
  {
    name: 'Faroe Islands',
    dialCode: '+298',
    code: 'FO',
    flag: '🇫🇴',
    regex: /^\d{6}$/,
  },
  { name: 'Fiji', dialCode: '+679', code: 'FJ', flag: '🇫🇯', regex: /^\d{7}$/ },
  {
    name: 'Finland',
    dialCode: '+358',
    code: 'FI',
    flag: '🇫🇮',
    regex: /^\d{5,12}$/,
  },
  { name: 'France', dialCode: '+33', code: 'FR', flag: '🇫🇷', regex: /^\d{9}$/ },
  {
    name: 'French Guiana',
    dialCode: '+594',
    code: 'GF',
    flag: '🇬🇫',
    regex: /^\d{9}$/,
  },
  {
    name: 'French Polynesia',
    dialCode: '+689',
    code: 'PF',
    flag: '🇵🇫',
    regex: /^\d{6,8}$/,
  },
  {
    name: 'Gabon',
    dialCode: '+241',
    code: 'GA',
    flag: '🇬🇦',
    regex: /^\d{7,8}$/,
  },
  {
    name: 'Gambia',
    dialCode: '+220',
    code: 'GM',
    flag: '🇬🇲',
    regex: /^\d{7}$/,
  },
  {
    name: 'Georgia',
    dialCode: '+995',
    code: 'GE',
    flag: '🇬🇪',
    regex: /^\d{9}$/,
  },
  {
    name: 'Germany',
    dialCode: '+49',
    code: 'DE',
    flag: '🇩🇪',
    regex: /^\d{10,11}$/,
  },
  {
    name: 'Ghana',
    dialCode: '+233',
    code: 'GH',
    flag: '🇬🇭',
    regex: /^\d{9,10}$/,
  },
  {
    name: 'Gibraltar',
    dialCode: '+350',
    code: 'GI',
    flag: '🇬🇮',
    regex: /^\d{8}$/,
  },
  {
    name: 'Greece',
    dialCode: '+30',
    code: 'GR',
    flag: '🇬🇷',
    regex: /^\d{10}$/,
  },
  {
    name: 'Greenland',
    dialCode: '+299',
    code: 'GL',
    flag: '🇬🇱',
    regex: /^\d{6}$/,
  },
  {
    name: 'Grenada',
    dialCode: '+1473',
    code: 'GD',
    flag: '🇬🇩',
    regex: REGEX_US,
  },
  {
    name: 'Guadeloupe',
    dialCode: '+590',
    code: 'GP',
    flag: '🇬🇵',
    regex: /^\d{9}$/,
  },
  { name: 'Guam', dialCode: '+1671', code: 'GU', flag: '🇬🇺', regex: REGEX_US },
  {
    name: 'Guatemala',
    dialCode: '+502',
    code: 'GT',
    flag: '🇬🇹',
    regex: /^\d{8}$/,
  },
  {
    name: 'Guernsey',
    dialCode: '+44',
    code: 'GG',
    flag: '🇬🇬',
    regex: REGEX_10,
  },
  {
    name: 'Guinea',
    dialCode: '+224',
    code: 'GN',
    flag: '🇬🇳',
    regex: /^\d{9}$/,
  },
  {
    name: 'Guinea-Bissau',
    dialCode: '+245',
    code: 'GW',
    flag: '🇬🇼',
    regex: /^\d{7,9}$/,
  },
  {
    name: 'Guyana',
    dialCode: '+592',
    code: 'GY',
    flag: '🇬🇾',
    regex: /^\d{7}$/,
  },
  { name: 'Haiti', dialCode: '+509', code: 'HT', flag: '🇭🇹', regex: /^\d{8}$/ },
  {
    name: 'Honduras',
    dialCode: '+504',
    code: 'HN',
    flag: '🇭🇳',
    regex: /^\d{8}$/,
  },
  {
    name: 'Hong Kong',
    dialCode: '+852',
    code: 'HK',
    flag: '🇭🇰',
    regex: /^\d{8}$/,
  },
  {
    name: 'Hungary',
    dialCode: '+36',
    code: 'HU',
    flag: '🇭🇺',
    regex: /^\d{9}$/,
  },
  {
    name: 'Iceland',
    dialCode: '+354',
    code: 'IS',
    flag: '🇮🇸',
    regex: /^\d{7}$/,
  },
  { name: 'India', dialCode: '+91', code: 'IN', flag: '🇮🇳', regex: REGEX_10 },
  {
    name: 'Indonesia',
    dialCode: '+62',
    code: 'ID',
    flag: '🇮🇩',
    regex: /^\d{9,12}$/,
  },
  { name: 'Iran', dialCode: '+98', code: 'IR', flag: '🇮🇷', regex: /^\d{10}$/ },
  { name: 'Iraq', dialCode: '+964', code: 'IQ', flag: '🇮🇶', regex: /^\d{10}$/ },
  {
    name: 'Ireland',
    dialCode: '+353',
    code: 'IE',
    flag: '🇮🇪',
    regex: /^\d{9,10}$/,
  },
  {
    name: 'Isle of Man',
    dialCode: '+44',
    code: 'IM',
    flag: '🇮🇲',
    regex: REGEX_10,
  },
  {
    name: 'Israel',
    dialCode: '+972',
    code: 'IL',
    flag: '🇮🇱',
    regex: /^\d{9}$/,
  },
  {
    name: 'Italy',
    dialCode: '+39',
    code: 'IT',
    flag: '🇮🇹',
    regex: /^\d{9,10}$/,
  },
  {
    name: 'Jamaica',
    dialCode: '+1876',
    code: 'JM',
    flag: '🇯🇲',
    regex: REGEX_US,
  },
  { name: 'Japan', dialCode: '+81', code: 'JP', flag: '🇯🇵', regex: REGEX_10 },
  { name: 'Jersey', dialCode: '+44', code: 'JE', flag: '🇯🇪', regex: REGEX_10 },
  {
    name: 'Jordan',
    dialCode: '+962',
    code: 'JO',
    flag: '🇯🇴',
    regex: /^\d{9}$/,
  },
  {
    name: 'Kazakhstan',
    dialCode: '+7',
    code: 'KZ',
    flag: '🇰🇿',
    regex: REGEX_10,
  },
  {
    name: 'Kenya',
    dialCode: '+254',
    code: 'KE',
    flag: '🇰🇪',
    regex: /^\d{9,10}$/,
  },
  {
    name: 'Kiribati',
    dialCode: '+686',
    code: 'KI',
    flag: '🇰🇮',
    regex: /^\d{8}$/,
  },
  {
    name: 'Korea, North',
    dialCode: '+850',
    code: 'KP',
    flag: '🇰🇵',
    regex: /^\d{8,10}$/,
  },
  {
    name: 'Korea, South',
    dialCode: '+82',
    code: 'KR',
    flag: '🇰🇷',
    regex: /^\d{9,11}$/,
  },
  {
    name: 'Kuwait',
    dialCode: '+965',
    code: 'KW',
    flag: '🇰🇼',
    regex: /^\d{8}$/,
  },
  {
    name: 'Kyrgyzstan',
    dialCode: '+996',
    code: 'KG',
    flag: '🇰🇬',
    regex: /^\d{9}$/,
  },
  {
    name: 'Laos',
    dialCode: '+856',
    code: 'LA',
    flag: '🇱🇦',
    regex: /^\d{8,10}$/,
  },
  {
    name: 'Latvia',
    dialCode: '+371',
    code: 'LV',
    flag: '🇱🇻',
    regex: /^\d{8}$/,
  },
  {
    name: 'Lebanon',
    dialCode: '+961',
    code: 'LB',
    flag: '🇱🇧',
    regex: /^\d{7,8}$/,
  },
  {
    name: 'Lesotho',
    dialCode: '+266',
    code: 'LS',
    flag: '🇱🇸',
    regex: /^\d{8}$/,
  },
  {
    name: 'Liberia',
    dialCode: '+231',
    code: 'LR',
    flag: '🇱🇷',
    regex: /^\d{7,8}$/,
  },
  { name: 'Libya', dialCode: '+218', code: 'LY', flag: '🇱🇾', regex: /^\d{9}$/ },
  {
    name: 'Liechtenstein',
    dialCode: '+423',
    code: 'LI',
    flag: '🇱🇮',
    regex: /^\d{7}$/,
  },
  {
    name: 'Lithuania',
    dialCode: '+370',
    code: 'LT',
    flag: '🇱🇹',
    regex: /^\d{8}$/,
  },
  {
    name: 'Luxembourg',
    dialCode: '+352',
    code: 'LU',
    flag: '🇱🇺',
    regex: /^\d{9}$/,
  },
  { name: 'Macao', dialCode: '+853', code: 'MO', flag: '🇲🇴', regex: /^\d{8}$/ },
  {
    name: 'Macedonia',
    dialCode: '+389',
    code: 'MK',
    flag: '🇲🇰',
    regex: /^\d{8}$/,
  },
  {
    name: 'Madagascar',
    dialCode: '+261',
    code: 'MG',
    flag: '🇲🇬',
    regex: /^\d{9}$/,
  },
  {
    name: 'Malawi',
    dialCode: '+265',
    code: 'MW',
    flag: '🇲🇼',
    regex: /^\d{7,9}$/,
  },
  {
    name: 'Malaysia',
    dialCode: '+60',
    code: 'MY',
    flag: '🇲🇾',
    regex: /^\d{9,10}$/,
  },
  {
    name: 'Maldives',
    dialCode: '+960',
    code: 'MV',
    flag: '🇲🇻',
    regex: /^\d{7}$/,
  },
  { name: 'Mali', dialCode: '+223', code: 'ML', flag: '🇲🇱', regex: /^\d{8}$/ },
  { name: 'Malta', dialCode: '+356', code: 'MT', flag: '🇲🇹', regex: /^\d{8}$/ },
  {
    name: 'Marshall Islands',
    dialCode: '+692',
    code: 'MH',
    flag: '🇲🇭',
    regex: /^\d{7}$/,
  },
  {
    name: 'Martinique',
    dialCode: '+596',
    code: 'MQ',
    flag: '🇲🇶',
    regex: /^\d{9}$/,
  },
  {
    name: 'Mauritania',
    dialCode: '+222',
    code: 'MR',
    flag: '🇲🇷',
    regex: /^\d{8}$/,
  },
  {
    name: 'Mauritius',
    dialCode: '+230',
    code: 'MU',
    flag: '🇲🇺',
    regex: /^\d{7,8}$/,
  },
  {
    name: 'Mayotte',
    dialCode: '+262',
    code: 'YT',
    flag: '🇾🇹',
    regex: /^\d{9}$/,
  },
  { name: 'Mexico', dialCode: '+52', code: 'MX', flag: '🇲🇽', regex: REGEX_10 },
  {
    name: 'Micronesia',
    dialCode: '+691',
    code: 'FM',
    flag: '🇫🇲',
    regex: /^\d{7}$/,
  },
  {
    name: 'Moldova',
    dialCode: '+373',
    code: 'MD',
    flag: '🇲🇩',
    regex: /^\d{8}$/,
  },
  {
    name: 'Monaco',
    dialCode: '+377',
    code: 'MC',
    flag: '🇲🇨',
    regex: /^\d{8,9}$/,
  },
  {
    name: 'Mongolia',
    dialCode: '+976',
    code: 'MN',
    flag: '🇲🇳',
    regex: /^\d{8}$/,
  },
  {
    name: 'Montenegro',
    dialCode: '+382',
    code: 'ME',
    flag: '🇲🇪',
    regex: /^\d{8}$/,
  },
  {
    name: 'Montserrat',
    dialCode: '+1664',
    code: 'MS',
    flag: '🇲🇸',
    regex: REGEX_US,
  },
  {
    name: 'Morocco',
    dialCode: '+212',
    code: 'MA',
    flag: '🇲🇦',
    regex: /^\d{9}$/,
  },
  {
    name: 'Mozambique',
    dialCode: '+258',
    code: 'MZ',
    flag: '🇲🇿',
    regex: /^\d{9}$/,
  },
  {
    name: 'Myanmar',
    dialCode: '+95',
    code: 'MM',
    flag: '🇲🇲',
    regex: /^\d{7,10}$/,
  },
  {
    name: 'Namibia',
    dialCode: '+264',
    code: 'NA',
    flag: '🇳🇦',
    regex: /^\d{6,10}$/,
  },
  { name: 'Nauru', dialCode: '+674', code: 'NR', flag: '🇳🇷', regex: /^\d{7}$/ },
  { name: 'Nepal', dialCode: '+977', code: 'NP', flag: '🇳🇵', regex: REGEX_10 },
  {
    name: 'Netherlands',
    dialCode: '+31',
    code: 'NL',
    flag: '🇳🇱',
    regex: REGEX_9,
  },
  {
    name: 'New Caledonia',
    dialCode: '+687',
    code: 'NC',
    flag: '🇳🇨',
    regex: /^\d{6}$/,
  },
  {
    name: 'New Zealand',
    dialCode: '+64',
    code: 'NZ',
    flag: '🇳🇿',
    regex: /^\d{8,10}$/,
  },
  {
    name: 'Nicaragua',
    dialCode: '+505',
    code: 'NI',
    flag: '🇳🇮',
    regex: /^\d{8}$/,
  },
  { name: 'Niger', dialCode: '+227', code: 'NE', flag: '🇳🇪', regex: /^\d{8}$/ },
  {
    name: 'Nigeria',
    dialCode: '+234',
    code: 'NG',
    flag: '🇳🇬',
    regex: /^\d{10,11}$/,
  },
  { name: 'Niue', dialCode: '+683', code: 'NU', flag: '🇳🇺', regex: /^\d{4}$/ },
  {
    name: 'Norfolk Island',
    dialCode: '+672',
    code: 'NF',
    flag: '🇳🇫',
    regex: /^\d{5,6}$/,
  },
  {
    name: 'Northern Mariana Islands',
    dialCode: '+1670',
    code: 'MP',
    flag: '🇲🇵',
    regex: REGEX_US,
  },
  { name: 'Norway', dialCode: '+47', code: 'NO', flag: '🇳🇴', regex: /^\d{8}$/ },
  { name: 'Oman', dialCode: '+968', code: 'OM', flag: '🇴🇲', regex: /^\d{8}$/ },
  {
    name: 'Pakistan',
    dialCode: '+92',
    code: 'PK',
    flag: '🇵🇰',
    regex: /^\d{10,11}$/,
  },
  { name: 'Palau', dialCode: '+680', code: 'PW', flag: '🇵🇼', regex: /^\d{7}$/ },
  {
    name: 'Palestine',
    dialCode: '+970',
    code: 'PS',
    flag: '🇵🇸',
    regex: /^\d{9}$/,
  },
  {
    name: 'Panama',
    dialCode: '+507',
    code: 'PA',
    flag: '🇵🇦',
    regex: /^\d{7,8}$/,
  },
  {
    name: 'Papua New Guinea',
    dialCode: '+675',
    code: 'PG',
    flag: '🇵🇬',
    regex: /^\d{8}$/,
  },
  {
    name: 'Paraguay',
    dialCode: '+595',
    code: 'PY',
    flag: '🇵🇾',
    regex: /^\d{9}$/,
  },
  { name: 'Peru', dialCode: '+51', code: 'PE', flag: '🇵🇪', regex: /^\d{9}$/ },
  {
    name: 'Philippines',
    dialCode: '+63',
    code: 'PH',
    flag: '🇵🇭',
    regex: REGEX_10,
  },
  {
    name: 'Pitcairn',
    dialCode: '+870',
    code: 'PN',
    flag: '🇵🇳',
    regex: REGEX_VARIABLE,
  },
  { name: 'Poland', dialCode: '+48', code: 'PL', flag: '🇵🇱', regex: /^\d{9}$/ },
  {
    name: 'Portugal',
    dialCode: '+351',
    code: 'PT',
    flag: '🇵🇹',
    regex: /^\d{9}$/,
  },
  {
    name: 'Puerto Rico',
    dialCode: '+1',
    code: 'PR',
    flag: '🇵🇷',
    regex: REGEX_10,
  },
  { name: 'Qatar', dialCode: '+974', code: 'QA', flag: '🇶🇦', regex: /^\d{8}$/ },
  {
    name: 'Reunion',
    dialCode: '+262',
    code: 'RE',
    flag: '🇷🇪',
    regex: /^\d{9}$/,
  },
  {
    name: 'Romania',
    dialCode: '+40',
    code: 'RO',
    flag: '🇷🇴',
    regex: /^\d{9}$/,
  },
  { name: 'Russia', dialCode: '+7', code: 'RU', flag: '🇷🇺', regex: REGEX_10 },
  {
    name: 'Rwanda',
    dialCode: '+250',
    code: 'RW',
    flag: '🇷🇼',
    regex: /^\d{9}$/,
  },
  {
    name: 'Saint Barthelemy',
    dialCode: '+590',
    code: 'BL',
    flag: '🇧🇱',
    regex: /^\d{9}$/,
  },
  {
    name: 'Saint Helena',
    dialCode: '+290',
    code: 'SH',
    flag: '🇸🇭',
    regex: /^\d{4,5}$/,
  },
  {
    name: 'Saint Kitts and Nevis',
    dialCode: '+1869',
    code: 'KN',
    flag: '🇰🇳',
    regex: REGEX_US,
  },
  {
    name: 'Saint Lucia',
    dialCode: '+1758',
    code: 'LC',
    flag: '🇱🇨',
    regex: REGEX_US,
  },
  {
    name: 'Saint Martin',
    dialCode: '+590',
    code: 'MF',
    flag: '🇲🇫',
    regex: /^\d{9}$/,
  },
  {
    name: 'Saint Pierre and Miquelon',
    dialCode: '+508',
    code: 'PM',
    flag: '🇵🇲',
    regex: /^\d{6}$/,
  },
  {
    name: 'Saint Vincent and the Grenadines',
    dialCode: '+1784',
    code: 'VC',
    flag: '🇻🇨',
    regex: REGEX_US,
  },
  { name: 'Samoa', dialCode: '+685', code: 'WS', flag: '🇼🇸', regex: /^\d{7}$/ },
  {
    name: 'San Marino',
    dialCode: '+378',
    code: 'SM',
    flag: '🇸🇲',
    regex: /^\d{6,10}$/,
  },
  {
    name: 'Sao Tome and Principe',
    dialCode: '+239',
    code: 'ST',
    flag: '🇸🇹',
    regex: /^\d{7}$/,
  },
  {
    name: 'Saudi Arabia',
    dialCode: '+966',
    code: 'SA',
    flag: '🇸🇦',
    regex: /^\d{9}$/,
  },
  {
    name: 'Senegal',
    dialCode: '+221',
    code: 'SN',
    flag: '🇸🇳',
    regex: /^\d{9}$/,
  },
  {
    name: 'Serbia',
    dialCode: '+381',
    code: 'RS',
    flag: '🇷🇸',
    regex: /^\d{8,9}$/,
  },
  {
    name: 'Seychelles',
    dialCode: '+248',
    code: 'SC',
    flag: '🇸🇨',
    regex: /^\d{7}$/,
  },
  {
    name: 'Sierra Leone',
    dialCode: '+232',
    code: 'SL',
    flag: '🇸🇱',
    regex: /^\d{8}$/,
  },
  {
    name: 'Singapore',
    dialCode: '+65',
    code: 'SG',
    flag: '🇸🇬',
    regex: REGEX_8,
  },
  {
    name: 'Sint Maarten',
    dialCode: '+1721',
    code: 'SX',
    flag: '🇸🇽',
    regex: REGEX_US,
  },
  {
    name: 'Slovakia',
    dialCode: '+421',
    code: 'SK',
    flag: '🇸🇰',
    regex: /^\d{9}$/,
  },
  {
    name: 'Slovenia',
    dialCode: '+386',
    code: 'SI',
    flag: '🇸🇮',
    regex: /^\d{8}$/,
  },
  {
    name: 'Solomon Islands',
    dialCode: '+677',
    code: 'SB',
    flag: '🇸🇧',
    regex: /^\d{5,7}$/,
  },
  {
    name: 'Somalia',
    dialCode: '+252',
    code: 'SO',
    flag: '🇸🇴',
    regex: /^\d{8,9}$/,
  },
  {
    name: 'South Africa',
    dialCode: '+27',
    code: 'ZA',
    flag: '🇿🇦',
    regex: REGEX_9,
  },
  {
    name: 'South Sudan',
    dialCode: '+211',
    code: 'SS',
    flag: '🇸🇸',
    regex: /^\d{9}$/,
  },
  { name: 'Spain', dialCode: '+34', code: 'ES', flag: '🇪🇸', regex: /^\d{9}$/ },
  {
    name: 'Sri Lanka',
    dialCode: '+94',
    code: 'LK',
    flag: '🇱🇰',
    regex: /^\d{9}$/,
  },
  { name: 'Sudan', dialCode: '+249', code: 'SD', flag: '🇸🇩', regex: /^\d{9}$/ },
  {
    name: 'Suriname',
    dialCode: '+597',
    code: 'SR',
    flag: '🇸🇷',
    regex: /^\d{6,7}$/,
  },
  {
    name: 'Swaziland',
    dialCode: '+268',
    code: 'SZ',
    flag: '🇸🇿',
    regex: /^\d{7,8}$/,
  },
  {
    name: 'Sweden',
    dialCode: '+46',
    code: 'SE',
    flag: '🇸🇪',
    regex: /^\d{7,13}$/,
  },
  {
    name: 'Switzerland',
    dialCode: '+41',
    code: 'CH',
    flag: '🇨🇭',
    regex: /^\d{9}$/,
  },
  {
    name: 'Syria',
    dialCode: '+963',
    code: 'SY',
    flag: '🇸🇾',
    regex: /^\d{8,10}$/,
  },
  {
    name: 'Taiwan',
    dialCode: '+886',
    code: 'TW',
    flag: '🇹🇼',
    regex: /^\d{9}$/,
  },
  {
    name: 'Tajikistan',
    dialCode: '+992',
    code: 'TJ',
    flag: '🇹🇯',
    regex: /^\d{9}$/,
  },
  {
    name: 'Tanzania',
    dialCode: '+255',
    code: 'TZ',
    flag: '🇹🇿',
    regex: /^\d{9}$/,
  },
  {
    name: 'Thailand',
    dialCode: '+66',
    code: 'TH',
    flag: '🇹🇭',
    regex: /^\d{9}$/,
  },
  {
    name: 'Timor-Leste',
    dialCode: '+670',
    code: 'TL',
    flag: '🇹🇱',
    regex: /^\d{8}$/,
  },
  { name: 'Togo', dialCode: '+228', code: 'TG', flag: '🇹🇬', regex: /^\d{8}$/ },
  {
    name: 'Tokelau',
    dialCode: '+690',
    code: 'TK',
    flag: '🇹🇰',
    regex: /^\d{4,7}$/,
  },
  {
    name: 'Tonga',
    dialCode: '+676',
    code: 'TO',
    flag: '🇹🇴',
    regex: /^\d{5,7}$/,
  },
  {
    name: 'Trinidad and Tobago',
    dialCode: '+1868',
    code: 'TT',
    flag: '🇹🇹',
    regex: REGEX_US,
  },
  {
    name: 'Tunisia',
    dialCode: '+216',
    code: 'TN',
    flag: '🇹🇳',
    regex: /^\d{8}$/,
  },
  {
    name: 'Turkey',
    dialCode: '+90',
    code: 'TR',
    flag: '🇹🇷',
    regex: /^\d{10,11}$/,
  },
  {
    name: 'Turkmenistan',
    dialCode: '+993',
    code: 'TM',
    flag: '🇹🇲',
    regex: /^\d{8}$/,
  },
  {
    name: 'Turks and Caicos Islands',
    dialCode: '+1649',
    code: 'TC',
    flag: '🇹🇨',
    regex: REGEX_US,
  },
  {
    name: 'Tuvalu',
    dialCode: '+688',
    code: 'TV',
    flag: '🇹🇻',
    regex: /^\d{5,6}$/,
  },
  {
    name: 'Uganda',
    dialCode: '+256',
    code: 'UG',
    flag: '🇺🇬',
    regex: /^\d{9}$/,
  },
  {
    name: 'Ukraine',
    dialCode: '+380',
    code: 'UA',
    flag: '🇺🇦',
    regex: /^\d{9}$/,
  },
  {
    name: 'United Arab Emirates',
    dialCode: '+971',
    code: 'AE',
    flag: '🇦🇪',
    regex: /^\d{9}$/,
  },
  {
    name: 'United Kingdom',
    dialCode: '+44',
    code: 'GB',
    flag: '🇬🇧',
    regex: /^\d{10,11}$/,
  },
  {
    name: 'United States',
    dialCode: '+1',
    code: 'US',
    flag: '🇺🇸',
    regex: REGEX_US,
  },
  {
    name: 'Uruguay',
    dialCode: '+598',
    code: 'UY',
    flag: '🇺🇾',
    regex: /^\d{8,9}$/,
  },
  {
    name: 'Uzbekistan',
    dialCode: '+998',
    code: 'UZ',
    flag: '🇺🇿',
    regex: /^\d{9}$/,
  },
  {
    name: 'Vanuatu',
    dialCode: '+678',
    code: 'VU',
    flag: '🇻🇺',
    regex: /^\d{5,7}$/,
  },
  {
    name: 'Venezuela',
    dialCode: '+58',
    code: 'VE',
    flag: '🇻🇪',
    regex: /^\d{10}$/,
  },
  {
    name: 'Vietnam',
    dialCode: '+84',
    code: 'VN',
    flag: '🇻🇳',
    regex: /^\d{9,10}$/,
  },
  {
    name: 'Virgin Islands, British',
    dialCode: '+1284',
    code: 'VG',
    flag: '🇻🇬',
    regex: REGEX_US,
  },
  {
    name: 'Virgin Islands, U.S.',
    dialCode: '+1340',
    code: 'VI',
    flag: '🇻🇮',
    regex: REGEX_US,
  },
  {
    name: 'Wallis and Futuna',
    dialCode: '+681',
    code: 'WF',
    flag: '🇼🇫',
    regex: /^\d{6}$/,
  },
  { name: 'Yemen', dialCode: '+967', code: 'YE', flag: '🇾🇪', regex: /^\d{9}$/ },
  {
    name: 'Zambia',
    dialCode: '+260',
    code: 'ZM',
    flag: '🇿🇲',
    regex: /^\d{9}$/,
  },
  {
    name: 'Zimbabwe',
    dialCode: '+263',
    code: 'ZW',
    flag: '🇿🇼',
    regex: /^\d{9}$/,
  },
];

export const countryCurrencies = [
  { country: 'Afghanistan', countryCode: 'AF', currencies: ['AFN'] },
  { country: 'Albania', countryCode: 'AL', currencies: ['ALL'] },
  { country: 'Algeria', countryCode: 'DZ', currencies: ['DZD'] },
  { country: 'Andorra', countryCode: 'AD', currencies: ['EUR'] },
  { country: 'Angola', countryCode: 'AO', currencies: ['AOA'] },
  { country: 'Antigua and Barbuda', countryCode: 'AG', currencies: ['XCD'] },
  { country: 'Argentina', countryCode: 'AR', currencies: ['ARS'] },
  { country: 'Armenia', countryCode: 'AM', currencies: ['AMD'] },
  { country: 'Australia', countryCode: 'AU', currencies: ['AUD'] },
  { country: 'Austria', countryCode: 'AT', currencies: ['EUR'] },
  { country: 'Bahamas', countryCode: 'BS', currencies: ['BSD'] },
  { country: 'Bahrain', countryCode: 'BH', currencies: ['BHD'] },
  { country: 'Bangladesh', countryCode: 'BD', currencies: ['BDT'] },
  { country: 'Barbados', countryCode: 'BB', currencies: ['BBD'] },
  { country: 'Belarus', countryCode: 'BY', currencies: ['BYN'] },
  { country: 'Belgium', countryCode: 'BE', currencies: ['EUR'] },
  { country: 'Belize', countryCode: 'BZ', currencies: ['BZD'] },
  { country: 'Benin', countryCode: 'BJ', currencies: ['XOF'] },
  { country: 'Bhutan', countryCode: 'BT', currencies: ['BTN', 'INR'] },
  { country: 'Bolivia', countryCode: 'BO', currencies: ['BOB'] },
  { country: 'Bosnia and Herzegovina', countryCode: 'BA', currencies: ['BAM'] },
  { country: 'Botswana', countryCode: 'BW', currencies: ['BWP'] },
  { country: 'Brazil', countryCode: 'BR', currencies: ['BRL'] },
  { country: 'Brunei', countryCode: 'BN', currencies: ['BND', 'SGD'] },
  { country: 'Bulgaria', countryCode: 'BG', currencies: ['BGN'] },
  { country: 'Cambodia', countryCode: 'KH', currencies: ['KHR', 'USD'] },
  { country: 'Cameroon', countryCode: 'CM', currencies: ['XAF'] },
  { country: 'Canada', countryCode: 'CA', currencies: ['CAD'] },
  { country: 'Chile', countryCode: 'CL', currencies: ['CLP'] },
  { country: 'China', countryCode: 'CN', currencies: ['CNY'] },
  { country: 'Colombia', countryCode: 'CO', currencies: ['COP'] },
  { country: 'Costa Rica', countryCode: 'CR', currencies: ['CRC'] },
  { country: 'Croatia', countryCode: 'HR', currencies: ['EUR'] },
  { country: 'Cuba', countryCode: 'CU', currencies: ['CUP'] },
  { country: 'Cyprus', countryCode: 'CY', currencies: ['EUR'] },
  { country: 'Czech Republic', countryCode: 'CZ', currencies: ['CZK'] },
  { country: 'Denmark', countryCode: 'DK', currencies: ['DKK'] },
  { country: 'Dominican Republic', countryCode: 'DO', currencies: ['DOP'] },
  { country: 'Ecuador', countryCode: 'EC', currencies: ['USD'] },
  { country: 'Egypt', countryCode: 'EG', currencies: ['EGP'] },
  { country: 'El Salvador', countryCode: 'SV', currencies: ['USD'] },
  { country: 'Estonia', countryCode: 'EE', currencies: ['EUR'] },
  { country: 'Ethiopia', countryCode: 'ET', currencies: ['ETB'] },
  { country: 'Finland', countryCode: 'FI', currencies: ['EUR'] },
  { country: 'France', countryCode: 'FR', currencies: ['EUR'] },
  { country: 'Georgia', countryCode: 'GE', currencies: ['GEL'] },
  { country: 'Germany', countryCode: 'DE', currencies: ['EUR'] },
  { country: 'Ghana', countryCode: 'GH', currencies: ['GHS'] },
  { country: 'Greece', countryCode: 'GR', currencies: ['EUR'] },
  { country: 'Hong Kong', countryCode: 'HK', currencies: ['HKD'] },
  { country: 'Hungary', countryCode: 'HU', currencies: ['HUF'] },
  { country: 'Iceland', countryCode: 'IS', currencies: ['ISK'] },
  { country: 'India', countryCode: 'IN', currencies: ['INR'] },
  { country: 'Indonesia', countryCode: 'ID', currencies: ['IDR'] },
  { country: 'Iran', countryCode: 'IR', currencies: ['IRR'] },
  { country: 'Iraq', countryCode: 'IQ', currencies: ['IQD'] },
  { country: 'Ireland', countryCode: 'IE', currencies: ['EUR'] },
  { country: 'Israel', countryCode: 'IL', currencies: ['ILS'] },
  { country: 'Italy', countryCode: 'IT', currencies: ['EUR'] },
  { country: 'Japan', countryCode: 'JP', currencies: ['JPY'] },
  { country: 'Jordan', countryCode: 'JO', currencies: ['JOD'] },
  { country: 'Kenya', countryCode: 'KE', currencies: ['KES'] },
  { country: 'Kuwait', countryCode: 'KW', currencies: ['KWD'] },
  { country: 'Lebanon', countryCode: 'LB', currencies: ['LBP'] },
  { country: 'Lithuania', countryCode: 'LT', currencies: ['EUR'] },
  { country: 'Luxembourg', countryCode: 'LU', currencies: ['EUR'] },
  { country: 'Malaysia', countryCode: 'MY', currencies: ['MYR'] },
  { country: 'Maldives', countryCode: 'MV', currencies: ['MVR'] },
  { country: 'Mexico', countryCode: 'MX', currencies: ['MXN'] },
  { country: 'Morocco', countryCode: 'MA', currencies: ['MAD'] },
  { country: 'Nepal', countryCode: 'NP', currencies: ['NPR', 'INR'] },
  { country: 'Netherlands', countryCode: 'NL', currencies: ['EUR'] },
  { country: 'New Zealand', countryCode: 'NZ', currencies: ['NZD'] },
  { country: 'Nigeria', countryCode: 'NG', currencies: ['NGN'] },
  { country: 'Norway', countryCode: 'NO', currencies: ['NOK'] },
  { country: 'Oman', countryCode: 'OM', currencies: ['OMR'] },
  { country: 'Pakistan', countryCode: 'PK', currencies: ['PKR'] },
  { country: 'Philippines', countryCode: 'PH', currencies: ['PHP'] },
  { country: 'Poland', countryCode: 'PL', currencies: ['PLN'] },
  { country: 'Portugal', countryCode: 'PT', currencies: ['EUR'] },
  { country: 'Qatar', countryCode: 'QA', currencies: ['QAR'] },
  { country: 'Romania', countryCode: 'RO', currencies: ['RON'] },
  { country: 'Russia', countryCode: 'RU', currencies: ['RUB'] },
  { country: 'Saudi Arabia', countryCode: 'SA', currencies: ['SAR'] },
  { country: 'Singapore', countryCode: 'SG', currencies: ['SGD'] },
  { country: 'South Africa', countryCode: 'ZA', currencies: ['ZAR'] },
  { country: 'South Korea', countryCode: 'KR', currencies: ['KRW'] },
  { country: 'Spain', countryCode: 'ES', currencies: ['EUR'] },
  { country: 'Sri Lanka', countryCode: 'LK', currencies: ['LKR'] },
  { country: 'Sweden', countryCode: 'SE', currencies: ['SEK'] },
  { country: 'Switzerland', countryCode: 'CH', currencies: ['CHF'] },
  { country: 'Thailand', countryCode: 'TH', currencies: ['THB'] },
  { country: 'Turkey', countryCode: 'TR', currencies: ['TRY'] },
  { country: 'Ukraine', countryCode: 'UA', currencies: ['UAH'] },
  { country: 'United Arab Emirates', countryCode: 'AE', currencies: ['AED'] },
  { country: 'United Kingdom', countryCode: 'GB', currencies: ['GBP'] },
  { country: 'United States', countryCode: 'US', currencies: ['USD'] },
  { country: 'Vietnam', countryCode: 'VN', currencies: ['VND'] },
  { country: 'Yemen', countryCode: 'YE', currencies: ['YER'] },
  { country: 'Zimbabwe', countryCode: 'ZW', currencies: ['ZWL'] },
];

export const currencyCode = [
  'AFN',
  'ALL',
  'DZD',
  'EUR',
  'AOA',
  'XCD',
  'ARS',
  'AMD',
  'AUD',
  'EUR',
  'BSD',
  'BHD',
  'BDT',
  'BBD',
  'BYN',
  'EUR',
  'BZD',
  'XOF',
  'BTN',
  'INR',
  'BOB',
  'BAM',
  'BWP',
  'BRL',
  'BND',
  'SGD',
  'BGN',
  'KHR',
  'USD',
  'XAF',
  'CAD',
  'CLP',
  'CNY',
  'COP',
  'CRC',
  'EUR',
  'CUP',
  'EUR',
  'CZK',
  'DKK',
  'DOP',
  'USD',
  'EGP',
  'USD',
  'EUR',
  'ETB',
  'EUR',
  'EUR',
  'GEL',
  'EUR',
  'GHS',
  'EUR',
  'HKD',
  'HUF',
  'ISK',
  'INR',
  'IDR',
  'IRR',
  'IQD',
  'EUR',
  'ILS',
  'EUR',
  'JPY',
  'JOD',
  'KES',
  'KWD',
  'LBP',
  'EUR',
  'EUR',
  'MYR',
  'MVR',
  'MXN',
  'MAD',
  'NPR',
  'INR',
  'EUR',
  'NZD',
  'NGN',
  'NOK',
  'OMR',
  'PKR',
  'PHP',
  'PLN',
  'EUR',
  'QAR',
  'RON',
  'RUB',
  'SAR',
  'SGD',
  'ZAR',
  'KRW',
  'EUR',
  'LKR',
  'SEK',
  'CHF',
  'THB',
  'TRY',
  'UAH',
  'AED',
  'GBP',
  'USD',
  'VND',
  'YER',
  'ZWL',
];
